CONVERT_TO=rp2040_ce

ENCODER_MAP_ENABLE = yes
AUTO_SHIFT_ENABLE = no

# CAPS_WORD_ENABLE = yes
# COMMAND_ENABLE = no
# REPEAT_KEY_ENABLE = no
# AUDIO_ENABLE = no
# LAYER_LOCK_ENABLE = yes
# COMBO_ENABLE = yes
# EXTRAKEY_ENABLE = yes

OLED_ENABLE = no
RGBLIGHT_ENABLE = no

CONSOLE_ENABLE = yes
